{
    'name'                  : 'Biometric Device Integration',
    'version'               : '1.0',
    'summary'               : """Integrating Biometric Device With HR Attendance (Face + Thumb)""",
    'description'           : 'This module integrates Odoo with the biometric device. (Check below or README.md for compatible devices.)',
    'category'              : 'Generic Modules/Human Resources',
    "author"                :  "kelvzxu",
    "website"               :  "https://kltech-intl.odoo.com",
    'depends'               : ['base_setup', 'hr_attendance'],
    'data'                  : [
                                'security/ir.model.access.csv',
                                'views/zk_machine_view.xml',
                                'data/download_data.xml',
                                'views/css.xml',
                                'views/hr_attendance_view.xml',
                                'views/zk_attendance.xml',
                                'views/zk_user.xml',
                            ],
    'images'                : ['static/description/banner.png'],
    'license'               : 'AGPL-3',
    'demo'                  : [],
    'installable'           : True,
    'auto_install'          : False,
    'application'           : True,
    "price"                 :  30,
    "currency"              :  "EUR",
    "pre_init_hook"         :  "pre_init_check",
}
